/**
 * WTBeiboot SS2021 Patrick Albus
 * WTBeiboot SS2021 Patrick Albus
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FileDTO } from './fileDTO';

export interface DirectoryDTO { 
    directoryName?: string;
    directoryPath?: string;
    imageDataJson?: string;
    childDirectories?: Array<DirectoryDTO>;
    files?: Array<FileDTO>;
}